plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ezbookkeeping.widget'
    compileSdk 37

    defaultConfig {
        applicationId 'com.ezbookkeeping.widget'
        minSdk 23
        targetSdk 37
        versionCode 5
        versionName '1.0.4'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
